version: 0.3.7-{branch}-{build}

environment:
    global:
        RUST_BACKTRACE: full
        RUST_TEST_THREADS: 1
    matrix:
        - channel: nightly
          target: x86_64-pc-windows-msvc
          filename: k2-creek-x64.exe
        - channel: nightly
          target: i686-pc-windows-msvc
          filename: k2-creek-x86.exe

install:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs/
    - rustup-init.exe -y --default-host %target% --default-toolchain %channel%
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - rustc -vV
    - cargo -vV
    - rustup component add rustfmt-preview
    - rustup component add clippy-preview

cache:
    - '%USERPROFILE%\.cargo'

build: off

build_script: cargo build

test_script:
    - cargo fmt --all -- --check
    - cargo clippy --release -- -Dclippy -Dclippy_pedantic
    - cargo test --verbose --all -- --nocapture

after_test:
    - cargo build --release --verbose
    - ren target\release\k2-creek.exe %filename%

artifacts:
    - path: 'target/release/*.exe'

deploy:
    description: ''
    auth_token:
        secure: 5l5fHV5J1h7LjAFbbBN03PUA5mhoYkPKhHli4tuiZCSFh9Y4CUwq3Vtl9CynLby3
    provider: GitHub
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
