version: 0.5.0-{branch}-{build}

image:
    - Ubuntu
    - Visual Studio 2017

environment:
    global:
        RUST_BACKTRACE: full
        RUST_TEST_THREADS: 1
    matrix:
        - platform: x64
          target: x86_64-unknown-linux-gnu
          toolchain: nightly
        - platform: x64
          toolchain: nightly
          target: x86_64-pc-windows-msvc
          filename: k2-creek-x64.exe
          publish_artifact: true
        - platform: x86
          toolchain: nightly
          target: i686-pc-windows-msvc
          filename: k2-creek-x32.exe
          publish_artifact: true

matrix:
  exclude:
    - { image: Ubuntu,              target: x86_64-pc-windows-msvc }
    - { image: Ubuntu,              target: i686-pc-windows-msvc }
    - { image: Visual Studio 2017,  target: x86_64-unknown-linux-gnu }

install:
    - cmd: curl -sSf -o rustup-init.exe https://win.rustup.rs/
    - cmd: rustup-init.exe -y --default-host %target% --default-toolchain %toolchain%
    - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - sh: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-host $target --default-toolchain $toolchain
    - sh: export PATH="$HOME/.cargo/bin:$PATH"
    - rustc -vV
    - cargo -vV
    - rustup component add rustfmt-preview
    - rustup component add clippy-preview
    - sh: cargo install -f cargo-audit

cache:
    - '%USERPROFILE%\.cargo'
    - '$HOME/.cargo'

build: off

build_script: cargo build

test_script:
    - sh: cargo audit
    - sh: cargo fmt --all -- --check
    - sh: cargo clippy --all-targets -- -D warnings
    - cargo test --verbose --all -- --nocapture

after_test:
    - cmd: cargo build --release --verbose
    - cmd: ren target\release\k2-creek.exe %filename%

artifacts:
    - path: 'target/release/*.exe'

deploy:
    description: ''
    auth_token:
        secure: 5l5fHV5J1h7LjAFbbBN03PUA5mhoYkPKhHli4tuiZCSFh9Y4CUwq3Vtl9CynLby3
    provider: GitHub
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        publish_artifact: true
