[package]
name = "k2creek"
version = "0.2.1"
authors = ["Benjamin Wenzel <wenzel@ehealthexperts.de>",
           "Christian Fochler <fochler@ehealthexperts.de>"]

[dependencies]
encoding = "0.2.33"
reqwest = "0.8.1"
rust-ini = "0.10.0"
serde = "1.0.23"
serde_derive = "1.0.23"
serde_json = "1.0.6"

[dev-dependencies]
nv-xml = "0.1.3"
test-server = { git = "https://github.com/ChriFo/test-server-rs", tag = "v0.3.1" }
