[package]
name = "k2-creek"
version = "0.7.2"
authors = ["Benjamin Wenzel <wenzel@ehealthexperts.de>",
           "Christian Fochler <fochler@ehealthexperts.de>"]
license = "MIT"
homepage = "http://k2.ehealthexperts.de"
repository = "https://github.com/eHealthExperts/k2-creek.git"
publish = false
edition = "2018"

[dependencies]
antidote = "1.0.0"
base64 = "0.12.3"
der-parser = "4.0.2"
encoding = "0.2.33"
env_logger = "0.7.1"
failure = "0.1.8"
lazy_static = "1.4.0"
log = "0.4.11"
log-derive = "0.4.1"
nom = "5.1.2"
promptly = "0.3.0"
reqwest = { version = "0.10.7", features = ["blocking", "json"] }
rusticata-macros = "2.1.0"
serde = "1.0.114"
serde_derive = "1.0.114"
serde-xml-rs = "0.4.0"
treexml = { git = "https://github.com/ChriFo/treexml-rs", branch = "fix/defaultEncoding" }

[dependencies.config]
version = "0.10.1"
default-features = false
features = ["ini"]

[dev-dependencies]
nv-xml = "0.1.3"
serde_json = "1.0.57"
serial_test = "0.4.0"
test-server = { git = "https://github.com/ChriFo/test-server-rs", tag = "0.8.0" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"

[package.metadata.winres]
FileVersion = "0.7.2"
LegalCopyright = "eHealthExperts GmbH. All rights reserved."
ProductName = "K2 creek"
ProductVersion = "0.7.2"
