[package]
name = "k2-creek"
version = "0.4.1"
authors = ["Benjamin Wenzel <wenzel@ehealthexperts.de>",
           "Christian Fochler <fochler@ehealthexperts.de>"]
license = "MIT"
homepage = "http://k2.ehealthexperts.de"
repository = "https://github.com/eHealthExperts/k2-creek.git"
publish = false

[dependencies]
base64 = "0.9.3"
encoding = "0.2.33"
lazy_static = "1.1.0"
promptly = "0.1.5"
reqwest = "0.9.2"
rust-ini = "0.13.0"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.32"
treexml = { git = "https://github.com/ChriFo/treexml-rs", branch = "fix/defaultEncoding" }

[dev-dependencies]
nv-xml = "0.1.3"
test-server = { git = "https://github.com/ChriFo/test-server-rs", version = "0.5.3" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.6"

[package.metadata.winres]
FileVersion = "0.4.1"
LegalCopyright = "eHealthExperts GmbH. All rights reserved."
ProductName = "K2 creek"
ProductVersion = "0.4.1"
