[package]
name = "egk_xml_dump"
version = "0.1.0"
authors = ["Benjamin Wenzel <wenzel@ehealthexperts.de>"]

[dependencies]
reqwest = "0.8.1"
rust-ini = "0.10.0"
serde = "1.0.23"
serde_derive = "1.0.23"
serde_json = "1.0.6"
