[package]
name = "k2-creek"
version = "0.3.6"
authors = ["Benjamin Wenzel <wenzel@ehealthexperts.de>",
           "Christian Fochler <fochler@ehealthexperts.de>"]
license = "MIT"
homepage = "http://k2.ehealthexperts.de"
repository = "https://github.com/eHealthExperts/k2-creek.git"
publish = false

[dependencies]
base64 = "0.9.0"
encoding = "0.2.33"
reqwest = "0.8.4"
rust-ini = "0.10.0"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
treexml = { git = "https://github.com/ChriFo/treexml-rs", branch = "fix/defaultEncoding" }

[dev-dependencies]
nv-xml = "0.1.3"
test-server = { git = "https://github.com/ChriFo/test-server-rs", tag = "v0.2.0" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.5"

[package.metadata.winres]
FileVersion = "0.3.6"
LegalCopyright = "eHealthExperts GmbH. All rights reserved."
ProductName = "K2 creek"
ProductVersion = "0.3.6"
