[package]
name = "k2-creek"
version = "0.6.2"
authors = ["Benjamin Wenzel <wenzel@ehealthexperts.de>",
           "Christian Fochler <fochler@ehealthexperts.de>"]
license = "MIT"
homepage = "http://k2.ehealthexperts.de"
repository = "https://github.com/eHealthExperts/k2-creek.git"
publish = false
edition = "2018"

[dependencies]
base64 = "0.10.1"
der-parser = "1.1.1"
encoding = "0.2.33"
lazy_static = "1.3.0"
nom = { version = "4.2.3", features = ["verbose-errors"] }
promptly = "0.1.5"
reqwest = "0.9.17"
rusticata-macros = "1.1.0"
serde = "1.0.92"
serde_derive = "1.0.92"
serde_ini = "0.2.0"
serde-xml-rs = "0.3.1"
treexml = { git = "https://github.com/ChriFo/treexml-rs", branch = "fix/defaultEncoding" }

[dev-dependencies]
nv-xml = "0.1.3"
serde_json = "1.0.39"
test-server = { git = "https://github.com/ChriFo/test-server-rs", tag = "0.6.0" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.9"

[package.metadata.winres]
FileVersion = "0.6.2"
LegalCopyright = "eHealthExperts GmbH. All rights reserved."
ProductName = "K2 creek"
ProductVersion = "0.6.2"
