sign-commit = true
disable-push = true
upload-doc = false
no-dev-version = true
tag-message = "{{version}}"
tag-prefix = "v"
pre-release-commit-message = "{{version}}"
pre-release-replacements = [
    {file="Cargo.toml", search="FileVersion = \"[0-9\\.]+\"", replace="FileVersion = \"{{version}}\""},
    {file="Cargo.toml", search="ProductVersion = \"[0-9\\.]+\"", replace="ProductVersion = \"{{version}}\""},
    {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
]
